const API=localStorage.getItem('vsApi')||'http://localhost:4000';
const demo=[
{title:'Brasil: os melhores gols da rodada',channel:'Na Cara do Gol',views:1200000,time:'há 2 horas',duration:'10:24',icon:'⚽',category:'Futebol'},
{title:'Construindo um jogo do zero na Unreal Engine 5',channel:'Dev Brasil',views:428000,time:'há 5 horas',duration:'18:42',icon:'🎮',category:'Jogos'},
{title:'A história da tecnologia em 15 minutos',channel:'Mundo Tech',views:892000,time:'há 1 dia',duration:'15:07',icon:'💻',category:'Tecnologia'},
{title:'Música para estudar e relaxar',channel:'Som Livre',views:3800000,time:'há 2 dias',duration:'1:02:15',icon:'🎵',category:'Música'},
{title:'Como criar seu primeiro canal de vídeo',channel:'Criadores',views:211000,time:'há 3 dias',duration:'12:30',icon:'🎥',category:'Tecnologia'},
{title:'Gameplay: sobrevivência em mundo aberto',channel:'Nexus Games',views:675000,time:'há 4 dias',duration:'26:18',icon:'🕹️',category:'Jogos'},
{title:'Notícias do mundo — resumo do dia',channel:'Agora News',views:1700000,time:'há 6 horas',duration:'08:55',icon:'📰',category:'Notícias'},
{title:'Aprenda programação de forma simples',channel:'Código Fácil',views:334000,time:'há 1 semana',duration:'21:03',icon:'⌨️',category:'Tecnologia'}];
let videos=[...demo], current=null;
let history=JSON.parse(localStorage.getItem('vsHistory')||'[]'),saved=JSON.parse(localStorage.getItem('vsSaved')||'[]');
const $=s=>document.querySelector(s),grid=$('#videoGrid');
const token=()=>localStorage.getItem('vsToken');
const fmt=n=>n>=1e6?(n/1e6).toFixed(1).replace('.0','')+' mi visualizações':n>=1e3?Math.round(n/1e3)+' mil visualizações':`${n||0} visualizações`;
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2200)};
async function api(path,options={}){const headers={...(options.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;const r=await fetch(API+path,{...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Erro na API');return data;}
function persist(){localStorage.setItem('vsHistory',JSON.stringify(history));localStorage.setItem('vsSaved',JSON.stringify(saved));}
function render(list=videos){grid.innerHTML=list.length?list.map((v,i)=>`<article class="card" data-index="${i}"><div class="thumb">${v.thumbnailUrl?`<img src="${v.thumbnailUrl}" alt="">`:`<span>${v.icon||'▶'}</span>`}<span class="duration">${v.duration||''}</span></div><h3>${v.title}</h3><div class="meta"><b>${v.author?.name||v.channel||'Criador'}</b><br>${fmt(v.views)} • ${v.time||new Date(v.createdAt).toLocaleDateString('pt-BR')}</div></article>`).join(''):'<div class="empty">Nenhum vídeo encontrado.</div>';}
async function loadVideos(q=''){try{const remote=await api('/api/videos'+(q?`?q=${encodeURIComponent(q)}`:''));if(remote.length)videos=remote;else videos=[...demo];}catch{videos=[...demo]}render(videos)}
loadVideos();
async function openVideo(i){current=videos[i];if(!current)return;history=[current.id||i,...history.filter(x=>x!==(current.id||i))].slice(0,30);persist();$('#modalTitle').textContent=current.title;$('#modalMeta').textContent=`${current.author?.name||current.channel||'Criador'} • ${fmt(current.views)} • ${current.category||'Vídeo'}`;$('#saveBtn').textContent=saved.includes(current.id||i)?'✓ Salvo':'♡ Salvar';$('#playerArea').innerHTML=current.videoUrl?`<video controls autoplay playsinline src="${current.videoUrl.startsWith('/')?API+current.videoUrl:current.videoUrl}"></video>`:`<div class="fake-player">${current.icon||'▶'}<small>Vídeo de demonstração</small></div>`;try{const detail=current.id?await api('/api/videos/'+current.id):null;if(detail){current=detail;$('#playerArea').innerHTML=`<video controls autoplay playsinline src="${API+detail.videoUrl}"></video>`;renderComments(detail.comments||[]);}}catch{renderComments([])}$('#videoModal').classList.remove('hidden')}
function renderComments(cs){$('#comments').innerHTML=cs.length?cs.map(c=>`<div class="comment"><b>${c.user?.name||'Usuário'}</b><p>${c.body}</p></div>`).join(''):'<p class="muted">Seja o primeiro a comentar.</p>'}
grid.addEventListener('click',e=>{const c=e.target.closest('.card');if(c)openVideo(+c.dataset.index)});
$('#searchForm').onsubmit=async e=>{e.preventDefault();const q=$('#searchInput').value.trim();$('#sectionHeading').textContent=q?`Resultados para “${q}”`:'Recomendados';await loadVideos(q)};
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('hidden');$('#exploreBtn').onclick=()=>grid.scrollIntoView({behavior:'smooth'});$('#allBtn').onclick=()=>loadVideos();
$('#chips').onclick=e=>{if(e.target.tagName!=='BUTTON')return;document.querySelectorAll('#chips button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');const c=e.target.textContent;render(c==='Tudo'?videos:videos.filter(v=>v.category===c))};
$('#accountBtn').onclick=()=>$('#accountModal').classList.remove('hidden');
$('#registerBtn').onclick=async()=>{try{const data=await api('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#accountName').value,email:$('#accountEmail').value,password:$('#accountPassword').value})});localStorage.setItem('vsToken',data.token);localStorage.setItem('vsUser',JSON.stringify(data.user));$('#accountBtn').textContent=data.user.name[0].toUpperCase();$('#accountStatus').textContent=`Conectado como ${data.user.name}`;toast('Conta criada com sucesso')}catch(e){toast(e.message)}};
$('#loginBtn').onclick=async()=>{try{const data=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#accountEmail').value,password:$('#accountPassword').value})});localStorage.setItem('vsToken',data.token);localStorage.setItem('vsUser',JSON.stringify(data.user));$('#accountBtn').textContent=data.user.name[0].toUpperCase();$('#accountStatus').textContent=`Conectado como ${data.user.name}`;toast('Login realizado')}catch(e){toast(e.message)}};
$('#uploadBtn').onclick=()=>{if(!token()){toast('Entre na sua conta para enviar vídeos');$('#accountModal').classList.remove('hidden');return}$('#uploadModal').classList.remove('hidden')};
$('#publishBtn').onclick=async()=>{const file=$('#uploadFile').files[0],title=$('#uploadTitle').value.trim();if(!file||!title)return toast('Informe título e arquivo');const fd=new FormData();fd.append('video',file);fd.append('title',title);fd.append('description',$('#uploadDescription').value);$('#uploadStatus').textContent='Enviando vídeo...';try{const v=await api('/api/videos',{method:'POST',body:fd});$('#uploadStatus').textContent='Publicado!';videos.unshift(v);render(videos);toast('Vídeo publicado');}catch(e){toast(e.message);$('#uploadStatus').textContent='Falha no envio'}};
$('#likeBtn').onclick=async()=>{if(!token())return toast('Entre para curtir');if(!current?.id)return toast('Curtir disponível nos vídeos publicados');try{const r=await api(`/api/videos/${current.id}/like`,{method:'POST'});toast(r.liked?'Vídeo curtido':'Curtida removida')}catch(e){toast(e.message)}};
$('#saveBtn').onclick=()=>{const id=current?.id||videos.indexOf(current);saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];persist();$('#saveBtn').textContent=saved.includes(id)?'✓ Salvo':'♡ Salvar';toast('Lista de salvos atualizada')};
$('#subscribeBtn').onclick=async()=>{if(!token()||!current?.author?.id)return toast('Entre para se inscrever');try{const r=await api(`/api/channels/${current.author.id}/subscribe`,{method:'POST'});toast(r.subscribed?'Inscrito no canal':'Inscrição cancelada')}catch(e){toast(e.message)}};
$('#commentForm').onsubmit=async e=>{e.preventDefault();if(!token()||!current?.id)return toast('Entre para comentar');const body=$('#commentInput').value.trim();if(!body)return;try{const c=await api(`/api/videos/${current.id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body})});const old=current.comments||[];current.comments=[c,...old];renderComments(current.comments);$('#commentInput').value=''}catch(e){toast(e.message)}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.add('hidden')});
document.querySelectorAll('[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();const v=a.dataset.view;if(v==='history'){const ids=new Set(history);render(videos.filter(x=>ids.has(x.id)))}else if(v==='playlists'){render(videos.filter(x=>saved.includes(x.id)))}else if(v==='trending'){render([...videos].sort((a,b)=>(b.views||0)-(a.views||0)))}else loadVideos()});
$('#bellBtn').onclick=()=>toast('Nenhuma nova notificação');$('#settingsBtn').onclick=e=>{e.preventDefault();toast('Configurações do Studio em desenvolvimento')};$('#reportBtn').onclick=e=>{e.preventDefault();toast('Central de denúncias em desenvolvimento')};
