const API=localStorage.getItem('vsApi')||'http://localhost:4000';
const demoVideo='https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4';
const demo=[
{title:'Demonstração: vídeo em alta definição',channel:'VideoSnathan',views:1200000,time:'há 2 horas',duration:'00:30',icon:'🎬',category:'Tecnologia',videoUrl:demoVideo,description:'Vídeo público de demonstração do player.'},
{title:'Futebol: melhores momentos',channel:'Na Cara do Gol',views:980000,time:'há 5 horas',duration:'08:42',icon:'⚽',category:'Futebol',videoUrl:demoVideo},
{title:'Construindo um jogo na Unreal Engine 5',channel:'Dev Brasil',views:428000,time:'há 8 horas',duration:'18:42',icon:'🎮',category:'Jogos',videoUrl:demoVideo},
{title:'Música para estudar e relaxar',channel:'Som Livre',views:3800000,time:'há 1 dia',duration:'01:02:15',icon:'🎵',category:'Música',videoUrl:demoVideo},
{title:'Aprenda programação de forma simples',channel:'Código Fácil',views:334000,time:'há 2 dias',duration:'21:03',icon:'⌨️',category:'Educação',videoUrl:demoVideo},
{title:'Notícias do mundo — resumo do dia',channel:'Agora News',views:1700000,time:'há 3 horas',duration:'08:55',icon:'📰',category:'Notícias',videoUrl:demoVideo},
{title:'Gameplay: sobrevivência em mundo aberto',channel:'Nexus Games',views:675000,time:'há 4 dias',duration:'26:18',icon:'🕹️',category:'Jogos',videoUrl:demoVideo},
{title:'Como criar seu primeiro canal de vídeo',channel:'Criadores',views:211000,time:'há 5 dias',duration:'12:30',icon:'📹',category:'Tecnologia',videoUrl:demoVideo},
{title:'Ao vivo: comunidade VideoSnathan',channel:'VideoSnathan Live',views:87000,time:'agora',duration:'AO VIVO',icon:'🔴',category:'Ao vivo',videoUrl:demoVideo}
];
let videos=[...demo],current=null;
let history=JSON.parse(localStorage.getItem('vsHistory')||'[]'),saved=JSON.parse(localStorage.getItem('vsSaved')||'[]');
const $=s=>document.querySelector(s),grid=$('#videoGrid');
const token=()=>localStorage.getItem('vsToken');
const fmt=n=>n>=1e6?(n/1e6).toFixed(1).replace('.0','')+' mi visualizações':n>=1e3?Math.round(n/1e3)+' mil visualizações':`${n||0} visualizações`;
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2200)};
async function api(path,options={}){const headers={...(options.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;const r=await fetch(API+path,{...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Erro na API');return data}
function persist(){localStorage.setItem('vsHistory',JSON.stringify(history));localStorage.setItem('vsSaved',JSON.stringify(saved))}
function render(list=videos){grid.innerHTML=list.length?list.map((v,i)=>`<article class="card" data-index="${i}"><div class="thumb">${v.thumbnailUrl?`<img src="${v.thumbnailUrl}" alt="">`:`<span>${v.icon||'▶'}</span>`}<span class="duration">${v.duration||''}</span></div><h3>${v.title}</h3><div class="meta"><b>${v.author?.name||v.channel||'Criador'}</b><br>${fmt(v.views)} • ${v.time||new Date(v.createdAt||Date.now()).toLocaleDateString('pt-BR')}</div></article>`).join(''):'<div class="empty">Nenhum vídeo encontrado.</div>'}
async function loadVideos(q=''){try{const remote=await api('/api/videos'+(q?`?q=${encodeURIComponent(q)}`:''));if(Array.isArray(remote)&&remote.length)videos=remote;else videos=[...demo]}catch{videos=[...demo]}render(videos)}
loadVideos();
async function openVideo(i){current=videos[i];if(!current)return;const id=current.id||i;history=[id,...history.filter(x=>x!==id)].slice(0,30);persist();$('#modalTitle').textContent=current.title;$('#modalMeta').textContent=`${current.author?.name||current.channel||'Criador'} • ${fmt(current.views)} • ${current.category||'Vídeo'}`;$('#saveBtn').textContent=saved.includes(id)?'✓ Salvo':'♡ Salvar';const source=current.videoUrl?(current.videoUrl.startsWith('/')?API+current.videoUrl:current.videoUrl):null;$('#playerArea').innerHTML=source?`<video controls autoplay playsinline src="${source}"></video>`:`<div class="demo-player">${current.icon||'▶'}<small>Vídeo de demonstração</small></div>`;$('#likeBtn').querySelector('span').textContent=current.likes||0;try{if(current.id){const detail=await api('/api/videos/'+current.id);current=detail;const src=detail.videoUrl?(detail.videoUrl.startsWith('/')?API+detail.videoUrl:detail.videoUrl):null;if(src)$('#playerArea').innerHTML=`<video controls autoplay playsinline src="${src}"></video>`;renderComments(detail.comments||[]);}}catch{renderComments([])}$('#videoModal').classList.remove('hidden')}
function renderComments(cs){$('#comments').innerHTML=cs.length?cs.map(c=>`<div class="comment"><b>${c.user?.name||'Usuário'}</b><p>${c.body}</p></div>`).join(''):'<p class="muted">Seja o primeiro a comentar.</p>'}
grid.addEventListener('click',e=>{const c=e.target.closest('.card');if(c)openVideo(+c.dataset.index)});
$('#searchForm').onsubmit=async e=>{e.preventDefault();const q=$('#searchInput').value.trim();$('#sectionHeading').textContent=q?`Resultados para “${q}”`:'Vídeos recomendados';await loadVideos(q)};
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('hidden');$('#allBtn').onclick=()=>loadVideos();
$('#chips').onclick=e=>{if(e.target.tagName!=='BUTTON')return;document.querySelectorAll('#chips button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');const c=e.target.textContent;$('#sectionHeading').textContent=c==='Tudo'?'Vídeos recomendados':c;render(c==='Tudo'?videos:videos.filter(v=>v.category===c))};
$('#accountBtn').onclick=()=>$('#accountModal').classList.remove('hidden');
$('#registerBtn').onclick=async()=>{try{const data=await api('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#accountName').value,email:$('#accountEmail').value,password:$('#accountPassword').value})});localStorage.setItem('vsToken',data.token);localStorage.setItem('vsUser',JSON.stringify(data.user));$('#accountBtn').textContent=data.user.name[0].toUpperCase();$('#accountStatus').textContent=`Conectado como ${data.user.name}`;toast('Conta criada com sucesso')}catch(e){toast(e.message)}};
$('#loginBtn').onclick=async()=>{try{const data=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#accountEmail').value,password:$('#accountPassword').value})});localStorage.setItem('vsToken',data.token);localStorage.setItem('vsUser',JSON.stringify(data.user));$('#accountBtn').textContent=data.user.name[0].toUpperCase();$('#accountStatus').textContent=`Conectado como ${data.user.name}`;toast('Login realizado')}catch(e){toast(e.message)}};
$('#uploadBtn').onclick=()=>{if(!token()){toast('Entre na sua conta para enviar vídeos');$('#accountModal').classList.remove('hidden');return}$('#uploadModal').classList.remove('hidden')};
$('#publishBtn').onclick=async()=>{const file=$('#uploadFile').files[0],title=$('#uploadTitle').value.trim();if(!file||!title)return toast('Informe título e arquivo');const fd=new FormData();fd.append('video',file);fd.append('title',title);fd.append('description',$('#uploadDescription').value);$('#uploadStatus').textContent='Enviando vídeo...';try{const v=await api('/api/videos',{method:'POST',body:fd});$('#uploadStatus').textContent='Publicado!';videos.unshift(v);render(videos);toast('Vídeo publicado')}catch(e){toast(e.message);$('#uploadStatus').textContent='Falha no envio'}};
$('#likeBtn').onclick=async()=>{if(!token())return toast('Entre para curtir');if(!current?.id)return toast('Curtir estará disponível quando a API estiver conectada');try{const r=await api(`/api/videos/${current.id}/like`,{method:'POST'});$('#likeBtn').querySelector('span').textContent=r.likes||0;toast(r.liked?'Vídeo curtido':'Curtida removida')}catch(e){toast(e.message)}};
$('#saveBtn').onclick=()=>{const id=current?.id||videos.indexOf(current);saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];persist();$('#saveBtn').textContent=saved.includes(id)?'✓ Salvo':'♡ Salvar';toast('Vídeo salvo')};
$('#subscribeBtn').onclick=async()=>{if(!token()||!current?.author?.id)return toast('Entre para se inscrever');try{const r=await api(`/api/channels/${current.author.id}/subscribe`,{method:'POST'});toast(r.subscribed?'Inscrito no canal':'Inscrição cancelada')}catch(e){toast(e.message)}};
$('#commentForm').onsubmit=async e=>{e.preventDefault();if(!token()||!current?.id)return toast('Entre para comentar');const body=$('#commentInput').value.trim();if(!body)return;try{const c=await api(`/api/videos/${current.id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body})});current.comments=[c,...(current.comments||[])];renderComments(current.comments);$('#commentInput').value=''}catch(e){toast(e.message)}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.add('hidden')});
document.querySelectorAll('[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();const v=a.dataset.view;if(v==='history'){const ids=new Set(history);render(videos.filter(x=>ids.has(x.id||videos.indexOf(x))))}else if(v==='playlists'){render(videos.filter(x=>saved.includes(x.id||videos.indexOf(x))))}else if(v==='trending'){render([...videos].sort((a,b)=>(b.views||0)-(a.views||0)))}else render(videos)});
$('#bellBtn').onclick=()=>toast('Nenhuma nova notificação');$('#settingsBtn').onclick=e=>{e.preventDefault();toast('Configurações em desenvolvimento')};$('#reportBtn').onclick=e=>{e.preventDefault();toast('Central de denúncias em desenvolvimento')};
