const baseVideos=[
{title:'Brasil: os melhores gols da rodada',channel:'Na Cara do Gol',views:1200000,time:'há 2 horas',duration:'10:24',icon:'⚽',category:'Futebol'},
{title:'Construindo um jogo do zero na Unreal Engine 5',channel:'Dev Brasil',views:428000,time:'há 5 horas',duration:'18:42',icon:'🎮',category:'Jogos'},
{title:'A história da tecnologia em 15 minutos',channel:'Mundo Tech',views:892000,time:'há 1 dia',duration:'15:07',icon:'💻',category:'Tecnologia'},
{title:'Música para estudar e relaxar',channel:'Som Livre',views:3800000,time:'há 2 dias',duration:'1:02:15',icon:'🎵',category:'Música'},
{title:'Como criar seu primeiro canal de vídeo',channel:'Criadores',views:211000,time:'há 3 dias',duration:'12:30',icon:'🎥',category:'Tecnologia'},
{title:'Gameplay: sobrevivência em mundo aberto',channel:'Nexus Games',views:675000,time:'há 4 dias',duration:'26:18',icon:'🕹️',category:'Jogos'},
{title:'Notícias do mundo — resumo do dia',channel:'Agora News',views:1700000,time:'há 6 horas',duration:'08:55',icon:'📰',category:'Notícias'},
{title:'Aprenda programação de forma simples',channel:'Código Fácil',views:334000,time:'há 1 semana',duration:'21:03',icon:'⌨️',category:'Tecnologia'}
];
let videos=[...baseVideos,...JSON.parse(localStorage.getItem('vsVideos')||'[]')];
let history=JSON.parse(localStorage.getItem('vsHistory')||'[]'), saved=JSON.parse(localStorage.getItem('vsSaved')||'[]'), likes=JSON.parse(localStorage.getItem('vsLikes')||'{}'), comments=JSON.parse(localStorage.getItem('vsComments')||'{}'), subscriptions=JSON.parse(localStorage.getItem('vsSubs')||'[]');
const $=s=>document.querySelector(s), grid=$('#videoGrid');
const fmt=n=>n>=1e6?(n/1e6).toFixed(1).replace('.0','')+' mi visualizações':n>=1e3?Math.round(n/1e3)+' mil visualizações':n+' visualizações';
function persist(){localStorage.setItem('vsHistory',JSON.stringify(history));localStorage.setItem('vsSaved',JSON.stringify(saved));localStorage.setItem('vsLikes',JSON.stringify(likes));localStorage.setItem('vsComments',JSON.stringify(comments));localStorage.setItem('vsSubs',JSON.stringify(subscriptions));localStorage.setItem('vsVideos',JSON.stringify(videos.slice(baseVideos.length)));}
function render(list=videos){grid.innerHTML=list.length?list.map((v,i)=>`<article class="card" data-index="${videos.indexOf(v)}"><div class="thumb"><span>${v.icon||'▶'}</span><span class="duration">${v.duration||''}</span></div><h3>${v.title}</h3><div class="meta"><b>${v.channel}</b><br>${fmt(v.views||0)} • ${v.time||'agora'}</div></article>`).join(''):'<div class="empty">Nenhum vídeo encontrado.</div>';}
render();
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2200)}
function openVideo(index){const v=videos[index]; if(!v)return; history=[index,...history.filter(x=>x!==index)].slice(0,30); v.views=(v.views||0)+1; persist(); $('#modalTitle').textContent=v.title;$('#modalMeta').textContent=`${v.channel} • ${fmt(v.views)} • ${v.category||'Vídeo'}`;$('#likeBtn span').textContent=likes[index]||0;$('#saveBtn').textContent=saved.includes(index)?'✓ Salvo':'♡ Salvar';$('#subscribeBtn').textContent=subscriptions.includes(v.channel)?'✓ Inscrito':'Inscrever-se';$('#playerArea').innerHTML=v.fileUrl?`<video controls autoplay src="${v.fileUrl}"></video>`:`<div class="fake-player">${v.icon||'▶'}<small>Player de demonstração</small></div>`;renderComments(index);$('#videoModal').classList.remove('hidden');}
function renderComments(i){$('#comments').innerHTML=(comments[i]||[]).map(c=>`<div class="comment"><b>${c.user}</b><p>${c.text}</p></div>`).join('')||'<p class="muted">Seja o primeiro a comentar.</p>';}
grid.addEventListener('click',e=>{const card=e.target.closest('.card');if(card)openVideo(+card.dataset.index)});
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#searchInput').value.trim().toLowerCase();$('#sectionHeading').textContent=q?`Resultados para “${q}”`:'Recomendados';render(q?videos.filter(v=>(v.title+' '+v.channel+' '+v.category).toLowerCase().includes(q)):videos)});
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('hidden');$('#exploreBtn').onclick=()=>grid.scrollIntoView({behavior:'smooth'});$('#allBtn').onclick=()=>render();
$('#chips').onclick=e=>{if(e.target.tagName!=='BUTTON')return;document.querySelectorAll('#chips button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');const c=e.target.textContent;render(c==='Tudo'?videos:videos.filter(v=>v.category===c||(c==='Ao vivo'&&v.live)));};
$('#likeBtn').onclick=()=>{const i=videos.findIndex(v=>v.title===$('#modalTitle').textContent);likes[i]=(likes[i]||0)+1;$('#likeBtn span').textContent=likes[i];persist()};
$('#saveBtn').onclick=()=>{const i=videos.findIndex(v=>v.title===$('#modalTitle').textContent);saved=saved.includes(i)?saved.filter(x=>x!==i):[...saved,i];$('#saveBtn').textContent=saved.includes(i)?'✓ Salvo':'♡ Salvar';persist();toast(saved.includes(i)?'Vídeo salvo':'Removido dos salvos')};
$('#subscribeBtn').onclick=()=>{const v=videos.find(v=>v.title===$('#modalTitle').textContent);subscriptions=subscriptions.includes(v.channel)?subscriptions.filter(x=>x!==v.channel):[...subscriptions,v.channel];$('#subscribeBtn').textContent=subscriptions.includes(v.channel)?'✓ Inscrito':'Inscrever-se';persist()};
$('#commentForm').onsubmit=e=>{e.preventDefault();const input=$('#commentInput'),text=input.value.trim();if(!text)return;const i=videos.findIndex(v=>v.title===$('#modalTitle').textContent);comments[i]=[...(comments[i]||[]),{user:localStorage.getItem('vsUser')||'Visitante',text}];input.value='';persist();renderComments(i)};
$('#uploadBtn').onclick=()=>$('#uploadModal').classList.remove('hidden');$('#accountBtn').onclick=()=>$('#accountModal').classList.remove('hidden');
$('#loginBtn').onclick=()=>{const u=$('#username').value.trim();if(!u)return toast('Digite um nome de usuário');localStorage.setItem('vsUser',u);$('#accountStatus').textContent=`Conectado como ${u}`;$('#accountBtn').textContent=u[0].toUpperCase();toast('Conta local atualizada');};
$('#publishBtn').onclick=()=>{const title=$('#uploadTitle').value.trim(),file=$('#uploadFile').files[0],channel=$('#uploadChannel').value.trim()||'Meu canal';if(!title||!file)return toast('Informe título e arquivo de vídeo');const v={title,channel,views:0,time:'agora',duration:'',icon:'🎬',category:'Tudo',fileUrl:URL.createObjectURL(file)};videos.push(v);persist();render();$('#uploadStatus').textContent='Vídeo publicado nesta sessão do navegador.';toast('Vídeo publicado');};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.add('hidden')});
document.querySelectorAll('[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();const v=a.dataset.view;let list=videos,title='Recomendados';if(v==='history'){list=history.map(i=>videos[i]).filter(Boolean);title='Histórico'}if(v==='playlists'){list=saved.map(i=>videos[i]).filter(Boolean);title='Vídeos salvos'}if(v==='subscriptions'){list=videos.filter(x=>subscriptions.includes(x.channel));title='Inscrições'}if(v==='uploads'){list=videos.slice(baseVideos.length);title='Seus vídeos'}if(v==='trending'){list=[...videos].sort((a,b)=>(b.views||0)-(a.views||0));title='Em alta'}$('#sectionHeading').textContent=title;render(list)});
$('#bellBtn').onclick=()=>toast('Você não tem novas notificações');$('#settingsBtn').onclick=e=>{e.preventDefault();toast('Configurações serão adicionadas ao Studio')};$('#reportBtn').onclick=e=>{e.preventDefault();toast('Central de denúncias aberta em breve')};
